// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: 'http://localhost:8080' | (string & {});
};

/**
 * TODO 생성/수정 요청
 */
export type TodoRequest = {
    /**
     * TODO 제목
     */
    title: string;
    /**
     * TODO 설명
     */
    description?: string | null;
    /**
     * TODO 상태
     */
    status?: 'TODO' | 'IN_PROGRESS' | 'DONE';
    /**
     * 우선순위
     */
    priority?: 'HIGH' | 'MEDIUM' | 'LOW';
    /**
     * 마감일
     */
    dueDate?: string | null;
    /**
     * 정렬 순서
     */
    position?: number;
    /**
     * 프로젝트 ID (Phase 2)
     */
    projectId?: number | null;
};

/**
 * API 공통 응답
 */
export type ApiResponseTodoResponse = {
    /**
     * 성공 여부
     */
    success?: boolean;
    /**
     * 메시지
     */
    message?: string | null;
    /**
     * 응답 데이터
     */
    data?: TodoResponse | null;
};

/**
 * TODO 응답
 */
export type TodoResponse = {
    /**
     * TODO ID
     */
    id?: number | null;
    /**
     * 사용자 ID
     */
    userId?: number;
    /**
     * 사용자 이름
     */
    username?: string;
    /**
     * TODO 제목
     */
    title?: string;
    /**
     * TODO 설명
     */
    description?: string | null;
    /**
     * TODO 상태
     */
    status?: string;
    /**
     * 우선순위
     */
    priority?: string | null;
    /**
     * 마감일
     */
    dueDate?: string | null;
    /**
     * 완료일
     */
    completedAt?: string | null;
    /**
     * 정렬 순서
     */
    position?: number;
    /**
     * 프로젝트 ID (Phase 2)
     */
    projectId?: number | null;
    /**
     * 생성일
     */
    createdAt?: string;
    /**
     * 수정일
     */
    updatedAt?: string;
};

/**
 * 프로젝트 생성 요청 데이터
 */
export type ProjectRequest = {
    /**
     * 프로젝트명
     */
    name: string;
    /**
     * 프로젝트 설명
     */
    description?: string | null;
    /**
     * 프로젝트 색상 (HEX 코드)
     */
    color?: string;
    /**
     * 기본 프로젝트 여부
     */
    isDefault?: boolean;
    /**
     * 정렬 순서
     */
    position?: number;
};

/**
 * API 공통 응답
 */
export type ApiResponseProjectResponse = {
    /**
     * 성공 여부
     */
    success?: boolean;
    /**
     * 메시지
     */
    message?: string | null;
    /**
     * 응답 데이터
     */
    data?: ProjectResponse | null;
};

export type ProjectResponse = {
    /**
     * 프로젝트 ID
     */
    id?: number;
    /**
     * 프로젝트명
     */
    name?: string;
    /**
     * 프로젝트 설명
     */
    description?: string | null;
    /**
     * 프로젝트 색상 (HEX 코드)
     */
    color?: string;
    /**
     * 기본 프로젝트 여부
     */
    isDefault?: boolean;
    /**
     * 정렬 순서
     */
    position?: number;
    /**
     * 생성일시
     */
    createdAt?: string;
    /**
     * 수정일시
     */
    updatedAt?: string;
    /**
     * 프로젝트 내 TODO 개수
     */
    todoCount?: number;
};

/**
 * 회원가입 요청
 */
export type SignupRequest = {
    /**
     * 사용자 이름
     */
    username: string;
    /**
     * 이메일
     */
    email: string;
    /**
     * 비밀번호
     */
    password: string;
};

/**
 * API 공통 응답
 */
export type ApiResponseAuthResponse = {
    /**
     * 성공 여부
     */
    success?: boolean;
    /**
     * 메시지
     */
    message?: string | null;
    /**
     * 응답 데이터
     */
    data?: AuthResponse | null;
};

/**
 * 인증 응답
 */
export type AuthResponse = {
    /**
     * JWT 토큰
     */
    token?: string;
    /**
     * 토큰 타입
     */
    type?: string;
    /**
     * 사용자 이름
     */
    username?: string;
    /**
     * 이메일
     */
    email?: string;
    /**
     * 사용자 역할
     */
    role?: string;
};

/**
 * 로그인 요청
 */
export type LoginRequest = {
    /**
     * 사용자 이름
     */
    username: string;
    /**
     * 비밀번호
     */
    password: string;
};

/**
 * TODO 검색/필터링 요청
 */
export type TodoSearchRequest = {
    /**
     * 검색 키워드 (제목, 설명)
     */
    keyword?: string | null;
    /**
     * 상태 필터
     */
    status?: 'TODO' | 'IN_PROGRESS' | 'DONE';
    /**
     * 우선순위 필터
     */
    priority?: 'HIGH' | 'MEDIUM' | 'LOW';
    /**
     * 마감일 시작 범위
     */
    dueDateStart?: string | null;
    /**
     * 마감일 종료 범위
     */
    dueDateEnd?: string | null;
    /**
     * 정렬 필드
     */
    sortBy?: 'createdAt' | 'dueDate' | 'priority' | 'position' | 'title';
    /**
     * 정렬 방향
     */
    sortDirection?: 'ASC' | 'DESC';
    /**
     * 페이지 번호 (0부터 시작)
     */
    page?: number;
    /**
     * 페이지 크기
     */
    size?: number;
    /**
     * 프로젝트 ID 필터 (Phase 2)
     */
    projectId?: number | null;
};

/**
 * API 공통 응답
 */
export type ApiResponsePageTodoResponse = {
    /**
     * 성공 여부
     */
    success?: boolean;
    /**
     * 메시지
     */
    message?: string | null;
    /**
     * 응답 데이터
     */
    data?: PageTodoResponse | null;
};

export type PageTodoResponse = {
    totalPages?: number;
    totalElements?: number;
    size?: number;
    content?: Array<TodoResponse>;
    number?: number;
    sort?: SortObject;
    first?: boolean;
    last?: boolean;
    numberOfElements?: number;
    pageable?: PageableObject;
    empty?: boolean;
};

export type PageableObject = {
    offset?: number;
    sort?: SortObject;
    pageSize?: number;
    paged?: boolean;
    pageNumber?: number;
    unpaged?: boolean;
};

export type SortObject = {
    empty?: boolean;
    sorted?: boolean;
    unsorted?: boolean;
};

/**
 * API 공통 응답
 */
export type ApiResponseTodoStatsResponse = {
    /**
     * 성공 여부
     */
    success?: boolean;
    /**
     * 메시지
     */
    message?: string | null;
    /**
     * 응답 데이터
     */
    data?: TodoStatsResponse | null;
};

export type TodoStatsResponse = {
    totalCount?: number;
    todoCount?: number;
    inProgressCount?: number;
    doneCount?: number;
    overdueCount?: number;
    completionRate?: number;
};

/**
 * API 공통 응답
 */
export type ApiResponseTodoDashboardStatsResponse = {
    /**
     * 성공 여부
     */
    success?: boolean;
    /**
     * 메시지
     */
    message?: string | null;
    /**
     * 응답 데이터
     */
    data?: TodoDashboardStatsResponse | null;
};

export type BasicStats = {
    /**
     * 전체 개수
     */
    totalCount?: number;
    /**
     * 할 일 개수
     */
    todoCount?: number;
    /**
     * 진행중 개수
     */
    inProgressCount?: number;
    /**
     * 완료 개수
     */
    doneCount?: number;
    /**
     * 지난 마감일 개수
     */
    overdueCount?: number;
    /**
     * 완료율
     */
    completionRate?: number;
};

export type PriorityStats = {
    /**
     * 우선순위
     */
    priority?: string;
    /**
     * 개수
     */
    count?: number;
    /**
     * 비율 (%)
     */
    percentage?: number;
};

export type ProjectStats = {
    /**
     * 프로젝트 ID
     */
    projectId?: number | null;
    /**
     * 프로젝트 이름
     */
    projectName?: string;
    /**
     * 프로젝트 색상
     */
    projectColor?: string;
    /**
     * TODO 개수
     */
    todoCount?: number;
    /**
     * 비율 (%)
     */
    percentage?: number;
};

export type StatusStats = {
    /**
     * 상태
     */
    status?: string;
    /**
     * 개수
     */
    count?: number;
    /**
     * 비율 (%)
     */
    percentage?: number;
};

/**
 * 대시보드 통계 응답
 */
export type TodoDashboardStatsResponse = {
    /**
     * 기본 통계
     */
    basicStats?: BasicStats;
    /**
     * 상태별 통계
     */
    statusStats?: Array<StatusStats>;
    /**
     * 우선순위별 통계
     */
    priorityStats?: Array<PriorityStats>;
    /**
     * 프로젝트별 통계
     */
    projectStats?: Array<ProjectStats>;
};

/**
 * API 공통 응답
 */
export type ApiResponseListProjectResponse = {
    /**
     * 성공 여부
     */
    success?: boolean;
    /**
     * 메시지
     */
    message?: string | null;
    /**
     * 응답 데이터
     */
    data?: Array<ProjectResponse> | {
        [key: string]: unknown;
    } | null;
};

/**
 * API 공통 응답
 */
export type ApiResponseString = {
    /**
     * 성공 여부
     */
    success?: boolean;
    /**
     * 메시지
     */
    message?: string | null;
    /**
     * 응답 데이터
     */
    data?: string | {
        [key: string]: unknown;
    } | null;
};

/**
 * API 공통 응답
 */
export type ApiResponseVoid = {
    /**
     * 성공 여부
     */
    success?: boolean;
    /**
     * 메시지
     */
    message?: string | null;
    /**
     * 응답 데이터
     */
    data?: {
        [key: string]: unknown;
    } | null;
};

export type DeleteTodoData = {
    body?: never;
    path: {
        /**
         * TODO ID
         */
        todoId: number;
    };
    query?: never;
    url: '/api/todos/{todoId}';
};

export type DeleteTodoResponses = {
    /**
     * OK
     */
    200: ApiResponseVoid;
};

export type DeleteTodoResponse = DeleteTodoResponses[keyof DeleteTodoResponses];

export type GetTodoData = {
    body?: never;
    path: {
        /**
         * TODO ID
         */
        todoId: number;
    };
    query?: never;
    url: '/api/todos/{todoId}';
};

export type GetTodoResponses = {
    /**
     * OK
     */
    200: ApiResponseTodoResponse;
};

export type GetTodoResponse = GetTodoResponses[keyof GetTodoResponses];

export type UpdateTodoData = {
    body: TodoRequest;
    path: {
        /**
         * TODO ID
         */
        todoId: number;
    };
    query?: never;
    url: '/api/todos/{todoId}';
};

export type UpdateTodoResponses = {
    /**
     * OK
     */
    200: ApiResponseTodoResponse;
};

export type UpdateTodoResponse = UpdateTodoResponses[keyof UpdateTodoResponses];

export type DeleteProjectData = {
    body?: never;
    path: {
        /**
         * 프로젝트 ID
         */
        projectId: number;
    };
    query?: never;
    url: '/api/projects/{projectId}';
};

export type DeleteProjectErrors = {
    /**
     * 기본 프로젝트는 삭제 불가
     */
    400: ApiResponseVoid;
    /**
     * 인증 실패
     */
    401: ApiResponseVoid;
    /**
     * 프로젝트를 찾을 수 없음
     */
    404: ApiResponseVoid;
};

export type DeleteProjectError = DeleteProjectErrors[keyof DeleteProjectErrors];

export type DeleteProjectResponses = {
    /**
     * 프로젝트 삭제 성공
     */
    200: ApiResponseVoid;
};

export type DeleteProjectResponse = DeleteProjectResponses[keyof DeleteProjectResponses];

export type GetProjectData = {
    body?: never;
    path: {
        /**
         * 프로젝트 ID
         */
        projectId: number;
    };
    query?: never;
    url: '/api/projects/{projectId}';
};

export type GetProjectErrors = {
    /**
     * 인증 실패
     */
    401: ApiResponseProjectResponse;
    /**
     * 프로젝트를 찾을 수 없음
     */
    404: ApiResponseProjectResponse;
};

export type GetProjectError = GetProjectErrors[keyof GetProjectErrors];

export type GetProjectResponses = {
    /**
     * 프로젝트 조회 성공
     */
    200: ApiResponseProjectResponse;
};

export type GetProjectResponse = GetProjectResponses[keyof GetProjectResponses];

export type UpdateProjectData = {
    body: ProjectRequest;
    path: {
        /**
         * 프로젝트 ID
         */
        projectId: number;
    };
    query?: never;
    url: '/api/projects/{projectId}';
};

export type UpdateProjectErrors = {
    /**
     * 잘못된 요청 데이터
     */
    400: ApiResponseProjectResponse;
    /**
     * 인증 실패
     */
    401: ApiResponseProjectResponse;
    /**
     * 프로젝트를 찾을 수 없음
     */
    404: ApiResponseProjectResponse;
    /**
     * 프로젝트명 중복
     */
    409: ApiResponseProjectResponse;
};

export type UpdateProjectError = UpdateProjectErrors[keyof UpdateProjectErrors];

export type UpdateProjectResponses = {
    /**
     * 프로젝트 수정 성공
     */
    200: ApiResponseProjectResponse;
};

export type UpdateProjectResponse = UpdateProjectResponses[keyof UpdateProjectResponses];

export type GetTodosData = {
    body?: never;
    path?: never;
    query: {
        /**
         * 검색 조건
         */
        searchRequest: TodoSearchRequest;
    };
    url: '/api/todos';
};

export type GetTodosResponses = {
    /**
     * OK
     */
    200: ApiResponsePageTodoResponse;
};

export type GetTodosResponse = GetTodosResponses[keyof GetTodosResponses];

export type CreateTodoData = {
    body: TodoRequest;
    path?: never;
    query?: never;
    url: '/api/todos';
};

export type CreateTodoResponses = {
    /**
     * OK
     */
    200: ApiResponseTodoResponse;
};

export type CreateTodoResponse = CreateTodoResponses[keyof CreateTodoResponses];

export type GetProjectsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/projects';
};

export type GetProjectsErrors = {
    /**
     * 인증 실패
     */
    401: ApiResponseListProjectResponse;
};

export type GetProjectsError = GetProjectsErrors[keyof GetProjectsErrors];

export type GetProjectsResponses = {
    /**
     * 프로젝트 목록 조회 성공
     */
    200: ApiResponseListProjectResponse;
};

export type GetProjectsResponse = GetProjectsResponses[keyof GetProjectsResponses];

export type CreateProjectData = {
    body: ProjectRequest;
    path?: never;
    query?: never;
    url: '/api/projects';
};

export type CreateProjectErrors = {
    /**
     * 잘못된 요청 데이터
     */
    400: ApiResponseProjectResponse;
    /**
     * 인증 실패
     */
    401: ApiResponseProjectResponse;
    /**
     * 프로젝트명 중복
     */
    409: ApiResponseProjectResponse;
};

export type CreateProjectError = CreateProjectErrors[keyof CreateProjectErrors];

export type CreateProjectResponses = {
    /**
     * 프로젝트 생성 성공
     */
    201: ApiResponseProjectResponse;
};

export type CreateProjectResponse = CreateProjectResponses[keyof CreateProjectResponses];

export type SignupData = {
    body: SignupRequest;
    path?: never;
    query?: never;
    url: '/api/auth/signup';
};

export type SignupResponses = {
    /**
     * 회원가입 성공
     */
    201: ApiResponseAuthResponse;
};

export type SignupResponse = SignupResponses[keyof SignupResponses];

export type LoginData = {
    body: LoginRequest;
    path?: never;
    query?: never;
    url: '/api/auth/login';
};

export type LoginErrors = {
    /**
     * 인증 실패
     */
    401: ApiResponseAuthResponse;
};

export type LoginError = LoginErrors[keyof LoginErrors];

export type LoginResponses = {
    /**
     * 로그인 성공
     */
    200: ApiResponseAuthResponse;
};

export type LoginResponse = LoginResponses[keyof LoginResponses];

export type UpdateTodoStatusData = {
    body?: never;
    path: {
        /**
         * TODO ID
         */
        todoId: number;
    };
    query: {
        /**
         * 변경할 상태
         */
        status: 'TODO' | 'IN_PROGRESS' | 'DONE';
    };
    url: '/api/todos/{todoId}/status';
};

export type UpdateTodoStatusResponses = {
    /**
     * OK
     */
    200: ApiResponseTodoResponse;
};

export type UpdateTodoStatusResponse = UpdateTodoStatusResponses[keyof UpdateTodoStatusResponses];

export type GetUserStatsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/todos/stats';
};

export type GetUserStatsResponses = {
    /**
     * OK
     */
    200: ApiResponseTodoStatsResponse;
};

export type GetUserStatsResponse = GetUserStatsResponses[keyof GetUserStatsResponses];

export type GetDashboardStatsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/todos/dashboard/stats';
};

export type GetDashboardStatsResponses = {
    /**
     * OK
     */
    200: ApiResponseTodoDashboardStatsResponse;
};

export type GetDashboardStatsResponse = GetDashboardStatsResponses[keyof GetDashboardStatsResponses];

export type GetDefaultProjectData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/projects/default';
};

export type GetDefaultProjectErrors = {
    /**
     * 인증 실패
     */
    401: ApiResponseProjectResponse;
    /**
     * 기본 프로젝트가 없음
     */
    404: ApiResponseProjectResponse;
};

export type GetDefaultProjectError = GetDefaultProjectErrors[keyof GetDefaultProjectErrors];

export type GetDefaultProjectResponses = {
    /**
     * 기본 프로젝트 조회 성공
     */
    200: ApiResponseProjectResponse;
};

export type GetDefaultProjectResponse = GetDefaultProjectResponses[keyof GetDefaultProjectResponses];

export type TestData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/test';
};

export type TestResponses = {
    /**
     * OK
     */
    200: ApiResponseString;
};

export type TestResponse = TestResponses[keyof TestResponses];
