// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: 'http://localhost:8080' | (string & {});
};

/**
 * TODO 생성/수정 요청
 */
export type TodoRequest = {
    /**
     * TODO 제목
     */
    title: string;
    /**
     * TODO 설명
     */
    description?: string | null;
    /**
     * TODO 상태
     */
    status?: 'TODO' | 'IN_PROGRESS' | 'DONE';
    /**
     * 우선순위
     */
    priority?: 'HIGH' | 'MEDIUM' | 'LOW';
    /**
     * 마감일
     */
    dueDate?: string | null;
    /**
     * 정렬 순서
     */
    position?: number;
    /**
     * 프로젝트 ID (Phase 2)
     */
    projectId?: number | null;
};

/**
 * API 공통 응답
 */
export type ApiResponseTodoResponse = {
    /**
     * 성공 여부
     */
    success?: boolean;
    /**
     * 메시지
     */
    message?: string | null;
    /**
     * 응답 데이터
     */
    data?: TodoResponse | null;
};

/**
 * TODO 응답
 */
export type TodoResponse = {
    /**
     * TODO ID
     */
    id?: number | null;
    /**
     * 사용자 ID
     */
    userId?: number;
    /**
     * 사용자 이름
     */
    username?: string;
    /**
     * TODO 제목
     */
    title?: string;
    /**
     * TODO 설명
     */
    description?: string | null;
    /**
     * TODO 상태
     */
    status?: string;
    /**
     * 우선순위
     */
    priority?: string | null;
    /**
     * 마감일
     */
    dueDate?: string | null;
    /**
     * 완료일
     */
    completedAt?: string | null;
    /**
     * 정렬 순서
     */
    position?: number;
    /**
     * 프로젝트 ID (Phase 2)
     */
    projectId?: number | null;
    /**
     * 생성일
     */
    createdAt?: string;
    /**
     * 수정일
     */
    updatedAt?: string;
};

/**
 * 회원가입 요청
 */
export type SignupRequest = {
    /**
     * 사용자 이름
     */
    username: string;
    /**
     * 이메일
     */
    email: string;
    /**
     * 비밀번호
     */
    password: string;
};

/**
 * API 공통 응답
 */
export type ApiResponseAuthResponse = {
    /**
     * 성공 여부
     */
    success?: boolean;
    /**
     * 메시지
     */
    message?: string | null;
    /**
     * 응답 데이터
     */
    data?: AuthResponse | null;
};

/**
 * 인증 응답
 */
export type AuthResponse = {
    /**
     * JWT 토큰
     */
    token?: string;
    /**
     * 토큰 타입
     */
    type?: string;
    /**
     * 사용자 이름
     */
    username?: string;
    /**
     * 이메일
     */
    email?: string;
    /**
     * 사용자 역할
     */
    role?: string;
};

/**
 * 로그인 요청
 */
export type LoginRequest = {
    /**
     * 사용자 이름
     */
    username: string;
    /**
     * 비밀번호
     */
    password: string;
};

/**
 * TODO 검색/필터링 요청
 */
export type TodoSearchRequest = {
    /**
     * 검색 키워드 (제목, 설명)
     */
    keyword?: string | null;
    /**
     * 상태 필터
     */
    status?: 'TODO' | 'IN_PROGRESS' | 'DONE';
    /**
     * 우선순위 필터
     */
    priority?: 'HIGH' | 'MEDIUM' | 'LOW';
    /**
     * 마감일 시작 범위
     */
    dueDateStart?: string | null;
    /**
     * 마감일 종료 범위
     */
    dueDateEnd?: string | null;
    /**
     * 정렬 필드
     */
    sortBy?: 'createdAt' | 'dueDate' | 'priority' | 'position' | 'title';
    /**
     * 정렬 방향
     */
    sortDirection?: 'ASC' | 'DESC';
    /**
     * 페이지 번호 (0부터 시작)
     */
    page?: number;
    /**
     * 페이지 크기
     */
    size?: number;
    /**
     * 프로젝트 ID 필터 (Phase 2)
     */
    projectId?: number | null;
};

/**
 * API 공통 응답
 */
export type ApiResponsePageTodoResponse = {
    /**
     * 성공 여부
     */
    success?: boolean;
    /**
     * 메시지
     */
    message?: string | null;
    /**
     * 응답 데이터
     */
    data?: PageTodoResponse | null;
};

export type PageTodoResponse = {
    totalElements?: number;
    totalPages?: number;
    size?: number;
    content?: Array<TodoResponse>;
    number?: number;
    sort?: SortObject;
    first?: boolean;
    last?: boolean;
    numberOfElements?: number;
    pageable?: PageableObject;
    empty?: boolean;
};

export type PageableObject = {
    offset?: number;
    sort?: SortObject;
    paged?: boolean;
    pageNumber?: number;
    pageSize?: number;
    unpaged?: boolean;
};

export type SortObject = {
    empty?: boolean;
    sorted?: boolean;
    unsorted?: boolean;
};

/**
 * API 공통 응답
 */
export type ApiResponseTodoStatsResponse = {
    /**
     * 성공 여부
     */
    success?: boolean;
    /**
     * 메시지
     */
    message?: string | null;
    /**
     * 응답 데이터
     */
    data?: TodoStatsResponse | null;
};

export type TodoStatsResponse = {
    totalCount?: number;
    todoCount?: number;
    inProgressCount?: number;
    doneCount?: number;
    overdueCount?: number;
    completionRate?: number;
};

/**
 * API 공통 응답
 */
export type ApiResponseString = {
    /**
     * 성공 여부
     */
    success?: boolean;
    /**
     * 메시지
     */
    message?: string | null;
    /**
     * 응답 데이터
     */
    data?: string | {
        [key: string]: unknown;
    } | null;
};

/**
 * API 공통 응답
 */
export type ApiResponseVoid = {
    /**
     * 성공 여부
     */
    success?: boolean;
    /**
     * 메시지
     */
    message?: string | null;
    /**
     * 응답 데이터
     */
    data?: {
        [key: string]: unknown;
    } | null;
};

export type DeleteTodoData = {
    body?: never;
    path: {
        /**
         * TODO ID
         */
        todoId: number;
    };
    query?: never;
    url: '/api/todos/{todoId}';
};

export type DeleteTodoResponses = {
    /**
     * OK
     */
    200: ApiResponseVoid;
};

export type DeleteTodoResponse = DeleteTodoResponses[keyof DeleteTodoResponses];

export type GetTodoData = {
    body?: never;
    path: {
        /**
         * TODO ID
         */
        todoId: number;
    };
    query?: never;
    url: '/api/todos/{todoId}';
};

export type GetTodoResponses = {
    /**
     * OK
     */
    200: ApiResponseTodoResponse;
};

export type GetTodoResponse = GetTodoResponses[keyof GetTodoResponses];

export type UpdateTodoData = {
    body: TodoRequest;
    path: {
        /**
         * TODO ID
         */
        todoId: number;
    };
    query?: never;
    url: '/api/todos/{todoId}';
};

export type UpdateTodoResponses = {
    /**
     * OK
     */
    200: ApiResponseTodoResponse;
};

export type UpdateTodoResponse = UpdateTodoResponses[keyof UpdateTodoResponses];

export type GetTodosData = {
    body?: never;
    path?: never;
    query: {
        /**
         * 검색 조건
         */
        searchRequest: TodoSearchRequest;
    };
    url: '/api/todos';
};

export type GetTodosResponses = {
    /**
     * OK
     */
    200: ApiResponsePageTodoResponse;
};

export type GetTodosResponse = GetTodosResponses[keyof GetTodosResponses];

export type CreateTodoData = {
    body: TodoRequest;
    path?: never;
    query?: never;
    url: '/api/todos';
};

export type CreateTodoResponses = {
    /**
     * OK
     */
    200: ApiResponseTodoResponse;
};

export type CreateTodoResponse = CreateTodoResponses[keyof CreateTodoResponses];

export type SignupData = {
    body: SignupRequest;
    path?: never;
    query?: never;
    url: '/api/auth/signup';
};

export type SignupResponses = {
    /**
     * 회원가입 성공
     */
    201: ApiResponseAuthResponse;
};

export type SignupResponse = SignupResponses[keyof SignupResponses];

export type LoginData = {
    body: LoginRequest;
    path?: never;
    query?: never;
    url: '/api/auth/login';
};

export type LoginErrors = {
    /**
     * 인증 실패
     */
    401: ApiResponseAuthResponse;
};

export type LoginError = LoginErrors[keyof LoginErrors];

export type LoginResponses = {
    /**
     * 로그인 성공
     */
    200: ApiResponseAuthResponse;
};

export type LoginResponse = LoginResponses[keyof LoginResponses];

export type UpdateTodoStatusData = {
    body?: never;
    path: {
        /**
         * TODO ID
         */
        todoId: number;
    };
    query: {
        /**
         * 변경할 상태
         */
        status: 'TODO' | 'IN_PROGRESS' | 'DONE';
    };
    url: '/api/todos/{todoId}/status';
};

export type UpdateTodoStatusResponses = {
    /**
     * OK
     */
    200: ApiResponseTodoResponse;
};

export type UpdateTodoStatusResponse = UpdateTodoStatusResponses[keyof UpdateTodoStatusResponses];

export type GetUserStatsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/todos/stats';
};

export type GetUserStatsResponses = {
    /**
     * OK
     */
    200: ApiResponseTodoStatsResponse;
};

export type GetUserStatsResponse = GetUserStatsResponses[keyof GetUserStatsResponses];

export type TestData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/test';
};

export type TestResponses = {
    /**
     * OK
     */
    200: ApiResponseString;
};

export type TestResponse = TestResponses[keyof TestResponses];
