// This file is auto-generated by @hey-api/openapi-ts

import { z } from 'zod';

/**
 * TODO 생성/수정 요청
 */
export const zTodoRequest = z.object({
    title: z.string().min(0).max(255),
    description: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    status: z.optional(z.enum([
        'TODO',
        'IN_PROGRESS',
        'DONE'
    ])),
    priority: z.optional(z.enum([
        'HIGH',
        'MEDIUM',
        'LOW'
    ])),
    dueDate: z.optional(z.union([
        z.iso.datetime(),
        z.null()
    ])),
    position: z.optional(z.int()),
    projectId: z.optional(z.union([
        z.coerce.bigint(),
        z.null()
    ]))
});

/**
 * TODO 응답
 */
export const zTodoResponse = z.object({
    id: z.optional(z.union([
        z.coerce.bigint(),
        z.null()
    ])),
    userId: z.optional(z.coerce.bigint()),
    username: z.optional(z.string()),
    title: z.optional(z.string()),
    description: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    status: z.optional(z.string()),
    priority: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    dueDate: z.optional(z.union([
        z.iso.datetime(),
        z.null()
    ])),
    completedAt: z.optional(z.union([
        z.iso.datetime(),
        z.null()
    ])),
    position: z.optional(z.int()),
    projectId: z.optional(z.union([
        z.coerce.bigint(),
        z.null()
    ])),
    createdAt: z.optional(z.iso.datetime()),
    updatedAt: z.optional(z.iso.datetime())
});

/**
 * API 공통 응답
 */
export const zApiResponseTodoResponse = z.object({
    success: z.optional(z.boolean()),
    message: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    data: z.optional(z.union([
        zTodoResponse,
        z.null()
    ]))
});

/**
 * 프로젝트 생성 요청 데이터
 */
export const zProjectRequest = z.object({
    name: z.string().min(0).max(100),
    description: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    color: z.optional(z.string().regex(/^#[0-9A-Fa-f]{6}$/)),
    isDefault: z.optional(z.boolean()),
    position: z.optional(z.int())
});

export const zProjectResponse = z.object({
    id: z.optional(z.coerce.bigint()),
    name: z.optional(z.string()),
    description: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    color: z.optional(z.string()),
    isDefault: z.optional(z.boolean()),
    position: z.optional(z.int()),
    createdAt: z.optional(z.iso.datetime()),
    updatedAt: z.optional(z.iso.datetime()),
    todoCount: z.optional(z.coerce.bigint())
});

/**
 * API 공통 응답
 */
export const zApiResponseProjectResponse = z.object({
    success: z.optional(z.boolean()),
    message: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    data: z.optional(z.union([
        zProjectResponse,
        z.null()
    ]))
});

/**
 * 회원가입 요청
 */
export const zSignupRequest = z.object({
    username: z.string().min(3).max(50),
    email: z.string().min(1),
    password: z.string().min(6).max(2147483647)
});

/**
 * 인증 응답
 */
export const zAuthResponse = z.object({
    token: z.optional(z.string()),
    type: z.optional(z.string()),
    username: z.optional(z.string()),
    email: z.optional(z.string()),
    role: z.optional(z.string())
});

/**
 * API 공통 응답
 */
export const zApiResponseAuthResponse = z.object({
    success: z.optional(z.boolean()),
    message: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    data: z.optional(z.union([
        zAuthResponse,
        z.null()
    ]))
});

/**
 * 로그인 요청
 */
export const zLoginRequest = z.object({
    username: z.string().min(1),
    password: z.string().min(1)
});

/**
 * TODO 검색/필터링 요청
 */
export const zTodoSearchRequest = z.object({
    keyword: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    status: z.optional(z.enum([
        'TODO',
        'IN_PROGRESS',
        'DONE'
    ])),
    priority: z.optional(z.enum([
        'HIGH',
        'MEDIUM',
        'LOW'
    ])),
    dueDateStart: z.optional(z.union([
        z.iso.datetime(),
        z.null()
    ])),
    dueDateEnd: z.optional(z.union([
        z.iso.datetime(),
        z.null()
    ])),
    sortBy: z.optional(z.enum([
        'createdAt',
        'dueDate',
        'priority',
        'position',
        'title'
    ])),
    sortDirection: z.optional(z.enum([
        'ASC',
        'DESC'
    ])),
    page: z.optional(z.int()),
    size: z.optional(z.int()),
    projectId: z.optional(z.union([
        z.coerce.bigint(),
        z.null()
    ]))
});

export const zSortObject = z.object({
    empty: z.optional(z.boolean()),
    sorted: z.optional(z.boolean()),
    unsorted: z.optional(z.boolean())
});

export const zPageableObject = z.object({
    offset: z.optional(z.coerce.bigint()),
    sort: z.optional(zSortObject),
    pageSize: z.optional(z.int()),
    paged: z.optional(z.boolean()),
    pageNumber: z.optional(z.int()),
    unpaged: z.optional(z.boolean())
});

export const zPageTodoResponse = z.object({
    totalPages: z.optional(z.int()),
    totalElements: z.optional(z.coerce.bigint()),
    size: z.optional(z.int()),
    content: z.optional(z.array(zTodoResponse)),
    number: z.optional(z.int()),
    sort: z.optional(zSortObject),
    first: z.optional(z.boolean()),
    last: z.optional(z.boolean()),
    numberOfElements: z.optional(z.int()),
    pageable: z.optional(zPageableObject),
    empty: z.optional(z.boolean())
});

/**
 * API 공통 응답
 */
export const zApiResponsePageTodoResponse = z.object({
    success: z.optional(z.boolean()),
    message: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    data: z.optional(z.union([
        zPageTodoResponse,
        z.null()
    ]))
});

export const zTodoStatsResponse = z.object({
    totalCount: z.optional(z.coerce.bigint()),
    todoCount: z.optional(z.coerce.bigint()),
    inProgressCount: z.optional(z.coerce.bigint()),
    doneCount: z.optional(z.coerce.bigint()),
    overdueCount: z.optional(z.coerce.bigint()),
    completionRate: z.optional(z.number())
});

/**
 * API 공통 응답
 */
export const zApiResponseTodoStatsResponse = z.object({
    success: z.optional(z.boolean()),
    message: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    data: z.optional(z.union([
        zTodoStatsResponse,
        z.null()
    ]))
});

/**
 * API 공통 응답
 */
export const zApiResponseListProjectResponse = z.object({
    success: z.optional(z.boolean()),
    message: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    data: z.optional(z.union([
        z.array(zProjectResponse),
        z.record(z.string(), z.unknown()),
        z.null()
    ]))
});

/**
 * API 공통 응답
 */
export const zApiResponseString = z.object({
    success: z.optional(z.boolean()),
    message: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    data: z.optional(z.union([
        z.string(),
        z.record(z.string(), z.unknown()),
        z.null()
    ]))
});

/**
 * API 공통 응답
 */
export const zApiResponseVoid = z.object({
    success: z.optional(z.boolean()),
    message: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    data: z.optional(z.union([
        z.record(z.string(), z.unknown()),
        z.null()
    ]))
});

export const zDeleteTodoData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        todoId: z.coerce.bigint()
    }),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zDeleteTodoResponse = zApiResponseVoid;

export const zGetTodoData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        todoId: z.coerce.bigint()
    }),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zGetTodoResponse = zApiResponseTodoResponse;

export const zUpdateTodoData = z.object({
    body: zTodoRequest,
    path: z.object({
        todoId: z.coerce.bigint()
    }),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zUpdateTodoResponse = zApiResponseTodoResponse;

export const zDeleteProjectData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        projectId: z.coerce.bigint()
    }),
    query: z.optional(z.never())
});

/**
 * 프로젝트 삭제 성공
 */
export const zDeleteProjectResponse = zApiResponseVoid;

export const zGetProjectData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        projectId: z.coerce.bigint()
    }),
    query: z.optional(z.never())
});

/**
 * 프로젝트 조회 성공
 */
export const zGetProjectResponse = zApiResponseProjectResponse;

export const zUpdateProjectData = z.object({
    body: zProjectRequest,
    path: z.object({
        projectId: z.coerce.bigint()
    }),
    query: z.optional(z.never())
});

/**
 * 프로젝트 수정 성공
 */
export const zUpdateProjectResponse = zApiResponseProjectResponse;

export const zGetTodosData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.object({
        searchRequest: zTodoSearchRequest
    })
});

/**
 * OK
 */
export const zGetTodosResponse = zApiResponsePageTodoResponse;

export const zCreateTodoData = z.object({
    body: zTodoRequest,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zCreateTodoResponse = zApiResponseTodoResponse;

export const zGetProjectsData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * 프로젝트 목록 조회 성공
 */
export const zGetProjectsResponse = zApiResponseListProjectResponse;

export const zCreateProjectData = z.object({
    body: zProjectRequest,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * 프로젝트 생성 성공
 */
export const zCreateProjectResponse = zApiResponseProjectResponse;

export const zSignupData = z.object({
    body: zSignupRequest,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * 회원가입 성공
 */
export const zSignupResponse = zApiResponseAuthResponse;

export const zLoginData = z.object({
    body: zLoginRequest,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * 로그인 성공
 */
export const zLoginResponse = zApiResponseAuthResponse;

export const zUpdateTodoStatusData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        todoId: z.coerce.bigint()
    }),
    query: z.object({
        status: z.enum([
            'TODO',
            'IN_PROGRESS',
            'DONE'
        ])
    })
});

/**
 * OK
 */
export const zUpdateTodoStatusResponse = zApiResponseTodoResponse;

export const zGetUserStatsData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zGetUserStatsResponse = zApiResponseTodoStatsResponse;

export const zGetDefaultProjectData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * 기본 프로젝트 조회 성공
 */
export const zGetDefaultProjectResponse = zApiResponseProjectResponse;

export const zTestData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zTestResponse = zApiResponseString;
