// This file is auto-generated by @hey-api/openapi-ts

import { z } from 'zod';

/**
 * TODO 생성/수정 요청
 */
export const zTodoRequest = z.object({
    title: z.string().min(0).max(255),
    description: z.optional(z.string()),
    status: z.optional(z.enum([
        'TODO',
        'IN_PROGRESS',
        'DONE'
    ])),
    priority: z.optional(z.enum([
        'HIGH',
        'MEDIUM',
        'LOW'
    ])),
    dueDate: z.optional(z.iso.datetime()),
    position: z.optional(z.int()),
    projectId: z.optional(z.coerce.bigint())
});

/**
 * TODO 응답
 */
export const zTodoResponse = z.object({
    id: z.optional(z.coerce.bigint()),
    userId: z.optional(z.coerce.bigint()),
    username: z.optional(z.string()),
    title: z.optional(z.string()),
    description: z.optional(z.string()),
    status: z.optional(z.string()),
    priority: z.optional(z.string()),
    dueDate: z.optional(z.iso.datetime()),
    completedAt: z.optional(z.iso.datetime()),
    position: z.optional(z.int()),
    projectId: z.optional(z.coerce.bigint()),
    createdAt: z.optional(z.iso.datetime()),
    updatedAt: z.optional(z.iso.datetime())
});

export const zApiResponseTodoResponse = z.object({
    success: z.optional(z.boolean()),
    message: z.optional(z.string()),
    data: z.optional(zTodoResponse)
});

export const zSignupRequest = z.object({
    username: z.string().min(3).max(50),
    email: z.string().min(1),
    password: z.string().min(6).max(2147483647)
});

export const zAuthResponse = z.object({
    token: z.optional(z.string()),
    type: z.optional(z.string()),
    username: z.optional(z.string()),
    email: z.optional(z.string()),
    role: z.optional(z.string())
});

export const zApiResponseAuthResponse = z.object({
    success: z.optional(z.boolean()),
    message: z.optional(z.string()),
    data: z.optional(zAuthResponse)
});

export const zLoginRequest = z.object({
    username: z.string().min(1),
    password: z.string().min(1)
});

/**
 * TODO 검색/필터링 요청
 */
export const zTodoSearchRequest = z.object({
    keyword: z.optional(z.string()),
    status: z.optional(z.enum([
        'TODO',
        'IN_PROGRESS',
        'DONE'
    ])),
    priority: z.optional(z.enum([
        'HIGH',
        'MEDIUM',
        'LOW'
    ])),
    dueDateStart: z.optional(z.iso.datetime()),
    dueDateEnd: z.optional(z.iso.datetime()),
    sortBy: z.optional(z.enum([
        'createdAt',
        'dueDate',
        'priority',
        'position',
        'title'
    ])),
    sortDirection: z.optional(z.enum([
        'ASC',
        'DESC'
    ])),
    page: z.optional(z.int()),
    size: z.optional(z.int()),
    projectId: z.optional(z.coerce.bigint())
});

export const zSortObject = z.object({
    empty: z.optional(z.boolean()),
    sorted: z.optional(z.boolean()),
    unsorted: z.optional(z.boolean())
});

export const zPageableObject = z.object({
    offset: z.optional(z.coerce.bigint()),
    sort: z.optional(zSortObject),
    paged: z.optional(z.boolean()),
    pageSize: z.optional(z.int()),
    pageNumber: z.optional(z.int()),
    unpaged: z.optional(z.boolean())
});

export const zPageTodoResponse = z.object({
    totalPages: z.optional(z.int()),
    totalElements: z.optional(z.coerce.bigint()),
    size: z.optional(z.int()),
    content: z.optional(z.array(zTodoResponse)),
    number: z.optional(z.int()),
    sort: z.optional(zSortObject),
    first: z.optional(z.boolean()),
    last: z.optional(z.boolean()),
    numberOfElements: z.optional(z.int()),
    pageable: z.optional(zPageableObject),
    empty: z.optional(z.boolean())
});

export const zApiResponsePageTodoResponse = z.object({
    success: z.optional(z.boolean()),
    message: z.optional(z.string()),
    data: z.optional(zPageTodoResponse)
});

export const zTodoStatsResponse = z.object({
    totalCount: z.optional(z.coerce.bigint()),
    todoCount: z.optional(z.coerce.bigint()),
    inProgressCount: z.optional(z.coerce.bigint()),
    doneCount: z.optional(z.coerce.bigint()),
    overdueCount: z.optional(z.coerce.bigint()),
    completionRate: z.optional(z.number())
});

export const zApiResponseTodoStatsResponse = z.object({
    success: z.optional(z.boolean()),
    message: z.optional(z.string()),
    data: z.optional(zTodoStatsResponse)
});

export const zApiResponseString = z.object({
    success: z.optional(z.boolean()),
    message: z.optional(z.string()),
    data: z.optional(z.string())
});

export const zApiResponseVoid = z.object({
    success: z.optional(z.boolean()),
    message: z.optional(z.string()),
    data: z.optional(z.unknown())
});

export const zDeleteTodoData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        todoId: z.coerce.bigint()
    }),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zDeleteTodoResponse = zApiResponseVoid;

export const zGetTodoData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        todoId: z.coerce.bigint()
    }),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zGetTodoResponse = zApiResponseTodoResponse;

export const zUpdateTodoData = z.object({
    body: zTodoRequest,
    path: z.object({
        todoId: z.coerce.bigint()
    }),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zUpdateTodoResponse = zApiResponseTodoResponse;

export const zGetTodosData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.object({
        searchRequest: zTodoSearchRequest
    })
});

/**
 * OK
 */
export const zGetTodosResponse = zApiResponsePageTodoResponse;

export const zCreateTodoData = z.object({
    body: zTodoRequest,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zCreateTodoResponse = zApiResponseTodoResponse;

export const zSignupData = z.object({
    body: zSignupRequest,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * 회원가입 성공
 */
export const zSignupResponse = zApiResponseAuthResponse;

export const zLoginData = z.object({
    body: zLoginRequest,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * 로그인 성공
 */
export const zLoginResponse = zApiResponseAuthResponse;

export const zUpdateTodoStatusData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        todoId: z.coerce.bigint()
    }),
    query: z.object({
        status: z.enum([
            'TODO',
            'IN_PROGRESS',
            'DONE'
        ])
    })
});

/**
 * OK
 */
export const zUpdateTodoStatusResponse = zApiResponseTodoResponse;

export const zGetUserStatsData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zGetUserStatsResponse = zApiResponseTodoStatsResponse;

export const zTestData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zTestResponse = zApiResponseString;
